version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.18.2

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with GCP
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $GCP_PROJECT_ID
      - run:
          name: Deploy to GCP Bucket
          command: |
            gsutil -m rsync -r build gs://$GCP_BUCKET_NAME

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # lancer le job
