version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.11.1  # ✅ version compatible avec firebase-tools

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Firebase CLI locally
          command: npm install firebase-tools
      - run:
          name: Deploy to Firebase Hosting
          command: npx firebase deploy --only hosting --token "$FIREBASE_TOKEN"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
