version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20  # Met à jour vers la version 20

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - firebase.json

  deploy:
    docker:
      - image: cimg/node:20  # Utilise la version 20
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Firebase CLI
          command: sudo npm install -g firebase-tools
      - run:
          name: Deploy to Firebase Hosting
          command: npx firebase deploy --only hosting --token "$FIREBASE_TOKEN"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # lancer le travail 
